package Exercises;

//REAJUSTE SALARIAL DE 8,75% , APARTIR DE DADOS INSERIDOS PELO USUÁRIO, CALCULE O SALÁRIO REAJUSTADO DE UM FUNCIONARIO, EXIBINDO
// COMO RESULTADO SEU NOME, O VALOR DO SALÁRIO ATUAL E O VALOR DO SALÁRIO REAJUSTADO.

public class reajuste {
    
}
